version: '3'
services:
  mongodb:
    image: mongo
    container_name: whatsapp-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  whatsapp-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-bot
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://root:example@mongodb:27017/whatsapp
    volumes:
      - ./session.json:/usr/src/app/session.json
    command: npm start
